language: scala
jdk:
  - oraclejdk8

sudo: required

dist: trusty
scala:
  - 2.12.10

env:
  global:
    - CCM_DIRECTORY=/home/travis/.ccm
  jobs:
    - CCM_CASSANDRA_VERSION=3.11.6

install:
  - pip install --user ccm

script:
  - "sbt ++$TRAVIS_SCALA_VERSION -Dtest.cassandra.version=$CASSANDRA_VERSION -Dtravis=true -Dtravis=true it:test"  #Integration Suite
  - "sbt ++$TRAVIS_SCALA_VERSION -Dtest.cassandra.version=$CASSANDRA_VERSION -Dtravis=true -Dtravis=true assembly" #Test Suite and Assembly Test
