language: scala
jdk:
  - oraclejdk8

sudo: required

dist: trusty

cache:
  directories:
    -  /home/travis/.ccm/repository

scala:
  - 2.12.10

env:
  global:
    - CCM_CLUSTER_MODE=debug
    - PRESERVE_LOGS=ccm
    - TEST_PARALLEL_TASKS=1
  jobs:
    - CCM_CASSANDRA_VERSION=3.11.6

install:
  - pip install --user ccm

script:
  - "sbt ++$TRAVIS_SCALA_VERSION -Dtravis=true it:test"  #Integration Suite
  - "sbt ++$TRAVIS_SCALA_VERSION -Dtravis=true assembly" #Test Suite and Assembly Test
